

# com.auth0.domain: dev-11fo0ea2adho6vqb.us.auth0.com
# com.auth0.clientId: SQ6iT4W1K8p4QYiXd484d9bCRdGEGTdX
# com.auth0.clientSecret: baKE4CV4_hXBGDfw2DaEQWkCJ_JskRhEo5a3kLRtWz3ER5w5C2lv01zCGZ9Ig43J

# logging:
#   level:
#     root: error
#     org.springframework.web: ERROR
#     com.example.auth0demoapplication: TRACE

# log file ganerate
# logging:
#     file:
#       name: MyAppLogs/myapp.log
#     level:
#         com:
#             infotech:
#                 com:
#                     infotech:
#                         app: info
#     root: error
#     org.springframework.web: ERROR
#     com.example.auth0demoapplication: TRACE
#     pattern:
#         console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
#         file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

logging:
    file:
      name: MyAppLogs/myapp.log
Configuration:
  status: info
  Appenders:
    Console:
      name: ConsoleAppender
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

    RollingFile:
      name: RollingFileAppender
      fileName: MyAppLogs/myapp.log
      filePattern: MyAppLogs/myapp-%d{yyyy-MM-dd}.%i.log
      append: true
      Policies:
        SizeBasedTriggeringPolicy:
          size: 10MB  # Set your desired log file size here
        DefaultRolloverStrategy:
          max: 7  # Number of archived log files to keep
      PatternLayout:
        Pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  Loggers:
    Root:
      level: error
      AppenderRef:
        - ref: RollingFileAppender

    Logger:
      - name: org.springframework.web
        level: error
        additivity: false
        AppenderRef:
          - ref: RollingFileAppender
      - name: com.example.auth0demoapplication
        level: trace
        additivity: false
        AppenderRef:
          - ref: RollingFileAppender

  AppenderRef:
    - ref: ConsoleAppender
    - ref: RollingFileAppender



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_board
    username: root
    password: 7410

    
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: UkrepWEIKkn2CIYLmGIiuU2fdwU34WdH
            client-secret: K1PDdEqQiWsbq5spsZNGKeYkHr6VTwCaBTWpo-RBLJXsD1L6d2W_OlryBd-c50Rw
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-2v6nqrql62h5dwnv.us.auth0.com/


  
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQL8Dialect